services:
  fastapi-app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
